### PR TITLE
 Fixed MySQL compatibility problems, added new filter feature for filtering like on non text fields

### PR DESCRIPTION
**Pull request by alechirsch**
This fixes the issue with other SQL syntax for columns on the LIKE filtering. I used the method as described in knex documentation here: [http://knexjs.org/#Raw-Bindings](http://knexjs.org/#Raw-Bindings).
This solved #26 

This also adds a new feature where you can search over any non text column with the like filtering, solves #37

### CODE REVIEW

**Comment by flmg** [comment]
It does work with PostgreSQL and SQLite but did you try with MySQL ? I don't think `CAST(:typeKey: AS text)` is working for it (it's expecting `CAST(:typeKey: AS CHAR)`)

**Comment by alechirsch** [comment]
I was looking at the docs for mysql, and I thought I saw text as a type. I should do more testing it seems.

**Comment by alechirsch** [comment]
What version of MySQL were you using? 

https://dev.mysql.com/doc/refman/5.7/en/blob.html

**Comment by flmg** [comment]
I use this tool http://sqlfiddle.com/ to check the syntax across multiple databases. So far I can't seem to find one syntax that works everywhere.

**Comment by alechirsch** [comment]
I just added some logic to determine which type to cast as. This should support MySQL, MS SQL, Postgres, SQLite.

**Review by flmg — APPROVED** [review]

**Pull request merged**
