### PR TITLE
Functions in 'filter' object to deal with range values

### PR DESCRIPTION
**Pull request by flmg**
Hello there,

I added support for using the 'upper' and 'lower' functions in the filter object like so:

    /events?filter[gte][lower(period)]='2018-04-18'

By doing so it solves the problem that arises when trying to filter on ranges such as date ranges in PostgreSQL. It could not be done using the existing filters, and adding range operators would make the lib less generic.

I used knex bindings to avoid any injection, added tests and updated the documentation.

Let me know if you have any question or remark, I'll be glad to update the pull request to get this shipped asap.

Thank you !

### CODE REVIEW

**Comment by alechirsch** [comment]
As far as I know, `lower` and `upper` only apply to strings, it throws an error if you attempt to apply it to a timestamp. I currently have date filtering working in my project by including the timestamp in the date like so
```
filter[gte][createdAt]: 2018-04-16T04:00:00.000Z
```

**Comment by flmg** [comment]
@alechirsch The `period` column in my example is actually a PostgreSQL range https://www.postgresql.org/docs/9.3/static/functions-range.html, which is quite different than a single timestamp.

It seems to me like a good way of dealing with those without adding some other filter type.

**Comment by jamesdixon** [comment]
@flmg thanks for the contribution!

My fear here is that we're starting to go too far down the rabbit hole with supporting calling functions and other things in the query string. For this case, I feel as this might be better handled outside of the scope of this addon. 

@alechirsch any thoughts? 

I'm open to suggestions, but this is what my gut is telling me.

**Comment by alechirsch** [comment]
Ah, I see now.
I agree this to going down a rabbit hole for extremely specific use cases. I also have concerns that it too heavily relies on assumptions made for postgres, and it only works for very specific column types.

**Comment by flmg** [comment]
I completely agree and appreciate the concern for the scope of this lib which is why I restricted the functions to only basic and shared SQL functions:

    const regex = new RegExp(/(.*)(count|sum|avg|max|min|lower|upper)\((.+)\)/g);

Even if ranges do not exist in MySQL for example, the `upper` and `lower` functions can be useful on string columns.

I am totally open to alternatives if you guys have ideas!

**Comment by jamesdixon** [comment]
One of the issues we ran into early on is that the JSONAPI spec doesn't define a DSL for filtering, so everyone has been left to create their own for the most part. It's a shame because it creates a disjointed effort in that regard when it comes to implementation.

@flmg appreciate the attention to detail here and I think there are some valid use cases to what you proposed. However, I'm still not sure if this is something we bake into the core functionality of this addon. 

I believe we'll need to think about this just a bit.

**Comment by flmg** [comment]
@jamesdixon Yes, the absence of spec for filtering is quite problematic 😀

Aside from those use cases, which I agree are somewhat advanced, I can also think of more basic features than one could expect such as combining filters with OR and AND (I know a discussion started about that some time ago: https://github.com/scoutforpets/bookshelf-jsonapi-params/issues/30).

What are your plans for the future of this library? How do you see it evolve regarding those use cases?

Thank you again for your time 🙏

**Comment by jamesdixon** [comment]
@flmg very problematic :)

> Aside from those use cases, which I agree are somewhat advanced, I can also think of more basic features than one could expect such as combining filters with OR and AND (I know a discussion started about that some time ago: #30).

Agreed. I believe this is a big one.

> What are your plans for the future of this library? How do you see it evolve regarding those use cases? 

Great question. My plans are very reactive. Basically, when I've needed this library to do something that it didn't support, I either added it or I found another way to do it. However, in all honesty, I'm working to move away from Bookshelf as an ORM, which has left any plans I did have for this library, to the wind.

I've already given @alechirsch the reigns so to speak and have only injected myself into the conversation here and there.

If both you and @alechirsch are sticking with Bookshelf, maybe it would be worth discussing he and you collaborating on this library going forward? I definitely don't want to stifle the development of this library going forward even if I do have differing opinions.

I would love to hear both of your thoughts.

Thanks again for the contributions, both with code and discussion!

**Comment by alechirsch** [comment]
I am sticking with Bookshelf for the foreseeable future here, I have been adding features as needed while trying to make them as generic as possible.

I am definitely open to having discussions on where we want to take this addon, including new features and limitations on what it should and should not handle. 

One feature I just published allows you to modify the query builder before knex executes the query, this is a great spot for doing very specific actions while still being able to use all of the other features that this addon provides. @flmg Considering looking into solving your use case using that additional query.

**Comment by alechirsch** [comment]
I am closing this PR for now

**Pull request closed without merging**
