### PR TITLE
Adding ability to perform `isNull`/`notNull` queries

### PR DESCRIPTION
**Pull request by shaneu**
We use this package at my company and while we find it very useful, we ran into the issue of being unable to check if a value in a table was null or not null. We were implementing filters to search if a particular scheduled event for a client was canceled or not. If the event was canceled there would have been a canceled_at date in the DB, or else null. Currently, as far as I could tell, there was no way to accomplish this type of query. 

With these proposed changes, a user would be able to structure a query like 
`filter.isNull = { column: 'canceled_at' };`. This has been working great in our application, and I feel there could be benefit here for other users.

Thank you for your consideration.

### CODE REVIEW

**Comment by alechirsch** [comment]
Passing in null to the filter should work
```
filter: {
  canceled_at: null
}
```
also

```
filter: {
  not: {
    canceled_at: null
  }
}
```

**Comment by shaneu** [comment]
That hasn't worked. That was my thinking initially as well, but when I tried that approach it ignored the filter and returned all results, regardless of wether they were canceled or not. I'm not sure exactly why this is the case, but I suspect that when that code is executed by the bookshelf-json-api package, no cases are matched and the code is just ignored.

**Comment by alechirsch** [comment]
Are you using json-api-query-parser for grabbing everything from the query parameters? I am certain that this package handles nulls correctly, however whatever you are using to parse the query could be interpreting `null` as a string and passing the string through instead of `null`.

**Comment by alechirsch** [comment]
This package uses `knex.where` for all equivalent operators, see here: [https://github.com/tgriesser/knex/blob/9f8d2eddbf4f42fe8c9fd9f2b2162a98d8cf2c12/src/query/builder.js#L230](https://github.com/tgriesser/knex/blob/9f8d2eddbf4f42fe8c9fd9f2b2162a98d8cf2c12/src/query/builder.js#L230)

`knex.where` handles the null case directly.

**Comment by alechirsch** [comment]
If it is the case that strings are getting through, you could write a small interpreter that changes all 'null' strings to the value `null` before passing in the filter to this package.

**Comment by alechirsch** [comment]
I took a second look at this.

This currently only supports if it is null, not if it is not null. See [here](https://github.com/scoutforpets/bookshelf-jsonapi-params/blob/df8cc5ea3cc70dce2cfad1f3a38c4c6a4659cc47/src/index.js#L437)


Not null does not work currently since we use `knex.whereNotIn` [here](https://github.com/scoutforpets/bookshelf-jsonapi-params/blob/df8cc5ea3cc70dce2cfad1f3a38c4c6a4659cc47/src/index.js#L412). Perhaps the way to solve this would be to use `knex.whereNotNull` if there is a `null` value.
```
else if (key === 'not'){
  if(_isNull(valueArray)){
    qb.whereNotNull(typeKey)
  }
  else {
    qb.whereNotIn(typeKey, valueArray);
  }
}
```
We currently have a test case for if something [is null](https://github.com/scoutforpets/bookshelf-jsonapi-params/blob/df8cc5ea3cc70dce2cfad1f3a38c4c6a4659cc47/test/index.js#L237)
@shaneu Could you write some test cases for querying if something is not null?

**Comment by alechirsch** [comment]
Closed, merged #47 instead

**Pull request closed without merging**
