### PR TITLE
Filter and Sort on related fields, filter by like, gt, lt, etc..

### PR DESCRIPTION
**Pull request by alechirsch**
This pull request has all of the functionality from #20, as well as an implementation for both #15 and #16. This is also related to #19.

### CODE REVIEW

**Comment by jamesdixon** [comment]
@alechirsch great work! I'm sorry I haven't been able to review yet. I will do so as soon as I can. Can you fix the tests and once that's done, I can take a look? Thank you!

**Comment by alechirsch** [comment]
@jamesdixon Thanks, I just fixed the tests.

**Comment by alechirsch** [comment]
I just found a bug where combining two relationship types on the same layer will produce duplicate results..

**Comment by jamesdixon** [comment]
Thanks, @alechirsch -- keep me posted.

**Comment by alechirsch** [comment]
@jamesdixon I fixed the bug, there was an error with how I handled the SQL 'or' operator

**Comment by alechirsch** [comment]
I can't seem to figure out why this failed. It says the timeout of 2000ms exceeded. Any ideas?

**Comment by jamesdixon** [comment]
@alechirsch going to try re-running the tests

**Comment by jamesdixon** [comment]
@alechirsch seems to be good now. Travis issue, I suppose

**Comment by jamesdixon** [comment]
@alechirsch was in the middle of reviewing this when some changes from @gmarkv10 came through. The tests are now failing.

**Comment by alechirsch** [comment]
@jamesdixon Those were all my changes, I have been finding bugs here and there. The test seems to have failed again because of a timeout, is there a way to increase the timeout limit?

**Comment by jamesdixon** [comment]
Not sure, but I'll re-run.

**Comment by jamesdixon** [comment]
@alechirsch there's a lot of code to review. That said, I don't have a ton of time. Given that you seem to have test cases for everything, I'm going to go ahead and merge. However, I'm going to release it under NPM as a 1.0 beta. That way, we can iron out any bugs that might come up. Sound good to you?

**Comment by alechirsch** [comment]
Sounds great to me! Thanks!

**Comment by jamesdixon** [comment]
Thank you! Really appreciate all of your hard work on this

**Comment by jamesdixon** [comment]
Should be installable via: `npm i bookshelf-jsonapi-params@beta`

**Comment by jamesdixon** [comment]
@alechirsch I haven't tested this in my own app as of yet. Just wanted to check-in and see how it was working for you?

**Comment by alechirsch** [comment]
@jamesdixon So far it is doing exactly what I wanted it to do and I have not found any more bugs as of yet. Please let me know what you think when you do use it.
The own of node-json-api-parser has not responding to my pull request. If you want to use my fork of the parser package, it is [here](https://github.com/alechirsch/node-jsonapi-query-parser)

**Comment by jamesdixon** [comment]
I installed it today and while I haven't used any of the advanced features, all existing functionality seem to work. Always a good sign 👍

**Comment by alechirsch** [comment]
This is indeed good news, I would love to hear feedback about the new
features when you use them.

**Pull request merged**
