### PR TITLE
Allow sorting by raw expressions

### PR DESCRIPTION
**Pull request by flmg**
Hi,

I added the possibility to provide advanced ordering expressions via the `sort` parameter as such:

    /entities?include=attribute&sort=-(attribute.name='test'),attribute.value

Or:
    
    /pets?sort=-(pets.weight < 100),pets.birthDate

Every expression in parentheses will be used as a raw _order by_ param when building the query.

Cheers 🎄

### CODE REVIEW

**Comment by alechirsch** [comment]
Isn't there danger of sql injection here?

**Comment by flmg** [comment]
@alechirsch True. Actually, I might be looking at it the wrong way. The problem I'm trying to solve is:

I have an `entities` table, each entity has many `attributes`, each attribute has a `name` and a `value`.

The question is, how can you order the entities based on one specific attribute? The solution proposed above could solve the problem, but I agree it is quite convoluted and not safe (I could restrict the parameter to basic/safe expressions, but that would be a compromise).

What do you think?

**Comment by alechirsch** [comment]
Is it a requirement that you have to put this in the http query itself? Or will you always be hitting the endpoint with this parameter?

**Comment by flmg** [comment]
@alechirsch The _attribute_ name and the ordering direction will vary, so I'm trying to find a syntax that would be as generic as possible.

**Comment by jamesdixon** [comment]
Hi guys -- i'm actually on holiday, but wanted to chime in quickly. I think we need to be careful of how "deep" this library goes. I'm all for flexibility, but I want to avoid making things too complex. I was okay with the aggregate functions, but ultimately I feel like some of these cases might be handled with alternate approaches. That said, I haven't done a full dive into this yet, but would love to hear thoughts.

Cheers.

**Comment by flmg** [comment]
Hi guys, I agree this is a bit out of scope for this library, so I'll close this PR. I'm still open to hear your thoughts on how to handle such a case though 🙂

**Pull request closed without merging**
